name: RustCI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-n-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install Maturin
      run: |
        pip install .
        pip install maturin

    - name: Build
      run: cargo build

    - name: Run tests
      run: cargo test

    - name: Build Wheels
      run: |
        maturin list-python
        maturin build --out wheels

    - name: Python extension test
      env:
        TEST_RUST_EXT: 1
        GA_OS: ${{ matrix.os }}
      run: |
        pip install setuptools
        pip install gapstat-rs --no-index --find-links wheels
        python setup.py test
